ALTER TABLE  DAE_NOTIFICHE_EVENTI
 ADD (Latitudine  NUMBER);

ALTER TABLE  DAE_NOTIFICHE_EVENTI
 ADD (longitudine  NUMBER);
 
 ALTER TABLE DAE_NOTIFICHE_EVENTI
 ADD (COORD_TIME_STAMP  TIMESTAMP(6));

ALTER TABLE DAE_NOTIFICHE_EVENTI
 ADD (TIPO_SELEZIONE  VARCHAR2(10));