/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CiclicalBookingDTO } from './ciclicalBookingDTO';


export interface CiclicalDTO { 
    ciclicalBooking?: CiclicalBookingDTO;
    id?: string;
    bookingId?: string;
    bookingCode?: string;
    fromDate?: Date;
    status?: string;
    toDate?: Date;
    parking?: string;
    transportDate?: string;
    modificationDate?: Date;
    modificationUser?: string;
    statusHistory?: string;
    createdBy?: string;
}
