/* Formatted on 14/02/2017 14:56:07 (QP5 v5.256.13226.35538) */
CREATE TABLE DAE_ENTE_CERTIFICATORE
(
   ID             VARCHAR2 (64) NOT NULL,
   DESCRIZIONE    VARCHAR2 (64),
   ONLY_FOR_MED   NUMBER (1) DEFAULT 0 NOT NULL,
   CONSTRAINT PK_DAE_ENTE_CERTIFICATORE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_PROFESSIONE
(
   ID            VARCHAR2 (64) NOT NULL,
   DESCRIZIONE   VARCHAR2 (200),
   CONSTRAINT PK_DAE_PROFESSIONE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_PROFILO_SANITARIO
(
   ID               VARCHAR2 (64) NOT NULL,
   ORDINE           VARCHAR2 (64) NOT NULL,
   NUM_ISCRIZIONE   VARCHAR2 (64) NOT NULL
);

CREATE TABLE DAE_CONFIG
(
   ID          VARCHAR2 (64) NOT NULL,
   PARAMETRO   VARCHAR2 (150) NOT NULL,
   VALORE      VARCHAR2 (150) NOT NULL,
   CONSTRAINT PK_DAE_CONFIG_ID PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_DAE_CONFIG_UNIQUE
   ON DAE_CONFIG (PARAMETRO);

CREATE TABLE DAE_COLORE
(
   ID             VARCHAR2 (64) NOT NULL,
   CATEGORIA_FR   VARCHAR2 (64),
   NOME_COLORE    VARCHAR2 (64),
   CONSTRAINT PK_DAE_COLORE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_PROVINCIA
(
   ID                      VARCHAR2 (50 BYTE) NOT NULL ENABLE,
   NOME_PROVINCIA          VARCHAR2 (256),
   CODICE_ISTAT            VARCHAR2 (3),
   DELETED                 NUMBER DEFAULT 0,
   SIGLA_AUTOMOBILISTICA   VARCHAR2 (2),
   CONSTRAINT PK_DAE_PROVINCIA_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_COMUNE
(
   ID             VARCHAR2 (64) NOT NULL,
   NOME_COMUNE    VARCHAR2 (64) NOT NULL,
   PROVINCIA_ID   VARCHAR2 (128) NOT NULL,
   CODICE_ISTAT   VARCHAR2 (6),
   DELETED        NUMBER DEFAULT 0,
   CONSTRAINT PK_DAE_COMUNE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_COMUNE_PROVINCIA_ID FOREIGN KEY
      (PROVINCIA_ID)
       REFERENCES DAE_PROVINCIA (ID)
);

CREATE TABLE DAE_QUESTIONARIO
(
   ID            VARCHAR2 (64) NOT NULL,
   DESCRIZIONE   VARCHAR2 (64),
   CONSTRAINT PK_DAE_QUESTIONARIO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_DOMANDA_QUESTIONARIO
(
   ID              VARCHAR2 (64) NOT NULL,
   QUESTIONARIO    VARCHAR2 (64),
   DOMANDA         VARCHAR2 (550),
   TIPO_RISPOSTA   VARCHAR2 (20),
   CONSTRAINT PK_DAE_DOMANDA_QUESTIONARIO_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DOMANDA_QUESTIONARIO_ID FOREIGN KEY
      (QUESTIONARIO)
       REFERENCES DAE_QUESTIONARIO (ID)
);

CREATE TABLE DAE_RISP_QUEST_FIRST_RESPONDER
(
   ID                             VARCHAR2 (64) NOT NULL,
   QUESTIONARIO_FIRST_RESPONDER   VARCHAR2 (64),
   DOMANDA_QUESTIONARIO           VARCHAR2 (64),
   RISPOSTA                       VARCHAR2 (4000),
   CONSTRAINT PK_DAE_RICH_QUEST_FRST_RESP_ID PRIMARY KEY (ID),
   CONSTRAINT FK_RISP_DOMANDA_QUEST_ID FOREIGN KEY
      (DOMANDA_QUESTIONARIO)
       REFERENCES DAE_DOMANDA_QUESTIONARIO (ID)
);

CREATE TABLE DAE_GPSLOCATION
(
   ID            VARCHAR2 (64) NOT NULL,
   LOCATION      VARCHAR2 (64),
   LATITUDINE    NUMBER,
   LONGITUDINE   NUMBER,
   ALTITUDINE    NUMBER,
   ERROR         NUMBER,
   TIME_STAMP    DATE,
   CONSTRAINT PK_DAE_GPSLOCATION_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_STRADE
(
   ID        VARCHAR2 (64 BYTE),
   COMUNE    VARCHAR2 (64 BYTE),
   NAME      VARCHAR2 (150 BYTE),
   NOTE      VARCHAR2 (1024 BYTE),
   DELETED   NUMBER DEFAULT 0,
   CONSTRAINT STRADE_PK PRIMARY KEY (ID),
   CONSTRAINT STRADE_R01 FOREIGN KEY
      (COMUNE)
       REFERENCES DAE_COMUNE (ID)
      ENABLE
);

CREATE INDEX IDX_STRADE_R01
   ON DAE_STRADE (COMUNE);

/*
CREATE INDEX CRASH_STRADE_R03
   ON DAE_STRADE (OLD_ID);

CREATE INDEX CRASH_STRADE_R04
   ON DAE_STRADE (UTENTE);
*/

CREATE TABLE DAE_LOCATION
(
   ID                    VARCHAR2 (64) NOT NULL,
   --COMUNEDO COMUNE,
   COMUNE                VARCHAR2 (64),
   INDIRIZZO             VARCHAR2 (64),
   CIVICO                VARCHAR2 (10),
   LUOGO_PUBBLICO        VARCHAR2 (64),
   TIPO_LUOGO_PUBBLICO   VARCHAR2 (20),
   GPSLOCATION           VARCHAR2 (64),
   CONSTRAINT PK_DAE_LOCATION_ID PRIMARY KEY (ID),
   CONSTRAINT FK_COMUNE_ID FOREIGN KEY (COMUNE) REFERENCES DAE_COMUNE (ID),
   CONSTRAINT FK_LOCATION_INDIRIZZO_ID FOREIGN KEY
      (INDIRIZZO)
       REFERENCES DAE_STRADE (ID),
   CONSTRAINT FK_LOCATION_GPSLOCATION_ID FOREIGN KEY
      (GPSLOCATION)
       REFERENCES DAE_GPSLOCATION (ID)
);

CREATE TABLE DAE_EVENT
(
   ID                       VARCHAR2 (64) NOT NULL,
   COORDINATE               VARCHAR2 (64),
   TELEFONO                 VARCHAR2 (64),
   CARTELLINO               VARCHAR2 (64),
   INFO                     VARCHAR2 (550),
   RIFERIMENTO              VARCHAR2 (250),
   NOTE                     VARCHAR2 (550),
   INDIRIZZO                VARCHAR2 (250),
   COMUNE                   VARCHAR2 (250),
   CIVICO                   VARCHAR2 (5),
   PROVINCIA                VARCHAR2 (150),
   CO_RIFERIMENTO           VARCHAR2 (550),
   CATEGORIA_ID             VARCHAR2 (128),
   TEMPO_ARRIVO_AMBULANZA   NUMBER,
   TIME_STAMP               DATE,
   DATA                     VARCHAR2 (20 BYTE),
   ABORT_DATE               TIMESTAMP (6),
   CLOSE_DATE               TIMESTAMP (6),
   CLOSED                   NUMBER,
   ACCEPTED_RESPONDERS      NUMBER,
   CONSTRAINT PK_DAE_EVENT_ID PRIMARY KEY (ID),
   CONSTRAINT FK_EVENT_GPS_LOCATION_ID FOREIGN KEY
      (COORDINATE)
       REFERENCES DAE_GPSLOCATION (ID)
);

CREATE TABLE DAE_STATO_UTENTE
(
   ID      VARCHAR2 (64) NOT NULL,
   STATO   VARCHAR2 (64),
   CONSTRAINT PK_DAE_STATO_UTENTE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_UTENTE
(
   ID                 VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER    VARCHAR2 (64),
   NOME               VARCHAR2 (150),
   COGNOME            VARCHAR2 (150),
   EMAIL              VARCHAR2 (64),
   CIVICO             VARCHAR2 (64),
   DATA_NASCITA       DATE,
   INDIRIZZO          VARCHAR2 (64),
   -- COMUNEDO COMUNERESIDENZA,
   COMUNE_RESIDENZA   VARCHAR2 (64),
   CAP                NUMBER (9),
   CODICE_FISCALE     VARCHAR2 (20),
   LANGUAGE           VARCHAR2 (20),
   LOGON              VARCHAR2 (250) NOT NULL,
   PASSWORD_HASH      VARCHAR2 (1024) NOT NULL,
   STATO_UTENTE       VARCHAR2 (64),
   IMMAGINE           VARCHAR2 (128),
   CONSTRAINT PK_DAE_UTENTE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_UTE_COMUNERESIDENZA_ID FOREIGN KEY
      (COMUNE_RESIDENZA)
       REFERENCES DAE_COMUNE (ID),
   CONSTRAINT FK_UTENTE_strade_ID FOREIGN KEY
      (INDIRIZZO)
       REFERENCES DAE_stRade (ID)
);

CREATE UNIQUE INDEX IDX_UTENTE_LOGON_unique
   ON DAE_UTENTE (LOGON);

CREATE TABLE DAE_GRUPPO
(
   ID            VARCHAR2 (64) NOT NULL,
   NOME_GRUPPO   VARCHAR2 (250),
   ID_PADRE      VARCHAR2 (64),
   ID_FIGLIO     VARCHAR2 (64),
   CONSTRAINT PK_DAE_GRUPPO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_IMAGE
(
   ID         VARCHAR2 (64) NOT NULL,
   DATA_B64   CLOB,
   CONSTRAINT PK_DAE_IMAGE_ID PRIMARY KEY (ID)
);


CREATE TABLE DAE_MAIL_TEMPLATE
(
   ID            VARCHAR2 (64) NOT NULL,
   NOME          VARCHAR2 (64),
   DESCRIZIONE   VARCHAR2 (1024),
   DATA_B64      CLOB,
   CONSTRAINT PK_DAE_MAIL_TEMPLATE_ID PRIMARY KEY (ID)
);


CREATE TABLE DAE_MAIL_TRACE
(
   ID                 VARCHAR2 (64) NOT NULL,
   DESTINATARIO       VARCHAR2 (64),
   MAIL_TEMPLATE_ID   VARCHAR2 (64),
   ENTITY_TYPE        VARCHAR2 (16),
   ENTITY_ID          VARCHAR2 (64),
   DATA_INVIO         DATE,
   CONSTRAINT PK_DAE_MAIL_TRACE_ID PRIMARY KEY (ID)
);


CREATE TABLE DAE_LOG_ALERT_DAE
(
   ID            VARCHAR2 (64) NOT NULL,
   DAE           VARCHAR2 (64) NOT NULL,
   TYPE          VARCHAR2 (64),
   DESCRIZIONE   VARCHAR2 (64),
   DATA          DATE,
   CONSTRAINT PK_DAE_LOG_ALERT_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_MANUTENTORE
(
   ID          VARCHAR2 (64) NOT NULL,
   NOME        VARCHAR2 (64),
   COGNOME     VARCHAR2 (64),
   INDIRIZZO   VARCHAR2 (64),
   COMUNE      VARCHAR2 (64),
   TEL         VARCHAR2 (64),
   EMAIL       VARCHAR2 (64),
   CONSTRAINT PK_DAE_MANUTENTORE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_MANUTENTORE_COMUNE_ID FOREIGN KEY
      (COMUNE)
       REFERENCES DAE_COMUNE (ID)
);

CREATE TABLE DAE_MAPPA_DAE_CONFIG
(
   ID                    VARCHAR2 (64) NOT NULL,
   TAGGIORNAMENTO        NUMBER (9),
   DECIMALI_MAPPE_GPS    NUMBER (9),
   ZOOM_INIZIALE_MAPPA   NUMBER (9),
   CONSTRAINT PK_DAE_MAPPA_DAE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_MESSAGGIO
(
   ID        VARCHAR2 (64) NOT NULL,
   TESTO     VARCHAR2 (4000),
   INVIO     DATE,
   DELETED   NUMBER DEFAULT 0,
   CONSTRAINT PK_DAE_MESSAGGIO_ID PRIMARY KEY (ID)
);


CREATE TABLE DAE_MESSAGGIO_FIRST_RESPONDER
(
   MESSAGGIO_ID         VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER_ID   VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_DAE_MESSAGGIO_MSG_FR_ID PRIMARY KEY
      (MESSAGGIO_ID, FIRST_RESPONDER_ID)
);

CREATE TABLE DAE_NOTA_DAE
(
   ID            VARCHAR2 (64) NOT NULL,
   DAE           VARCHAR2 (64),
   --GPSLOCATIONDO LOCATION,
   -- LOCATION VARCHAR2(64),
   DESCRIZIONE   VARCHAR2 (64),
   CONSTRAINT PK_DAE_NOTA_DAE_ID PRIMARY KEY (ID)
-- ,
-- CONSTRAINT FK_LOCATION_ID    FOREIGN KEY (LOCATION)    REFERENCES DAE_GPSLOCATION(ID)
);

CREATE TABLE DAE_TONO
(
   ID     VARCHAR2 (64) NOT NULL,
   NOME   VARCHAR2 (64),
   CONSTRAINT PK_DAE_TONO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_NOTIFICA
(
   ID                VARCHAR2 (64),
   ALIAS             VARCHAR2 (64),
   PNS_IDENTIFIER    VARCHAR2 (64),
   -- TONODO TONO ,
   TONO              VARCHAR2 (64) NOT NULL,
   PLATFORM          VARCHAR2 (64),
   MESSAGGIO         VARCHAR2 (64),
   REGISTRATION_ID   VARCHAR2 (64) NOT NULL,
   TAGS              VARCHAR2 (64),
   VALIDITA          DATE,
   --FIRSTRESPONDERDO PROPRIETA
   PROPRIETA         VARCHAR2 (64),
   LOG               NUMBER (9),
   VERSIONE          NUMBER (9),
   ULTIMARICHIESTA   DATE,
   CONSTRAINT PK_DAE_NOTIFICA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_TONO_ID FOREIGN KEY (TONO) REFERENCES DAE_TONO (ID)
);

CREATE TABLE DAE_NOTIFICHE_CONFIG
(
   ID                            VARCHAR2 (64) NOT NULL,
   AGGIUNGI_DATA_CREAZIONE       NUMBER (1) DEFAULT 0 NOT NULL,
   --TONODO AUDIOINTERVENTONUOVO,
   AUDIO_INTERVENTO_NUOVO        VARCHAR2 (64),
   AUDIO_INTERVENTO_AGGIORNATO   VARCHAR2 (64),
   AUDIO_INTERVENTO_ANNULLATO    VARCHAR2 (64),
   AUDIO_INTERVENTO_TERMINATO    VARCHAR2 (64),
   AUDIO_NEWS                    VARCHAR2 (64),
   AUDIO_CERTIFICATO_BLSDAE      VARCHAR2 (64),
   CONSTRAINT PK_DAE_NOTIFICHE_CONFIG_ID PRIMARY KEY (ID),
   CONSTRAINT FK_AUDIOINTERVENTONUOVO_ID FOREIGN KEY
      (AUDIO_INTERVENTO_NUOVO)
       REFERENCES DAE_TONO (ID),
   CONSTRAINT FK_AUDIONINTERVAGGIORNATO_ID FOREIGN KEY
      (AUDIO_INTERVENTO_AGGIORNATO)
       REFERENCES DAE_TONO (ID),
   CONSTRAINT FK_AUDIOINTERVENTOANNULLATO_ID FOREIGN KEY
      (AUDIO_INTERVENTO_ANNULLATO)
       REFERENCES DAE_TONO (ID),
   CONSTRAINT FK_AUDIOINTERVENTOTERMINATO_ID FOREIGN KEY
      (AUDIO_INTERVENTO_TERMINATO)
       REFERENCES DAE_TONO (ID),
   CONSTRAINT FK_AUDIONEWS_ID FOREIGN KEY
      (AUDIO_NEWS)
       REFERENCES DAE_TONO (ID),
   CONSTRAINT FK_AUDIOCERTIFICATOBLSDAE_ID FOREIGN KEY
      (AUDIO_CERTIFICATO_BLSDAE)
       REFERENCES DAE_TONO (ID)
);

CREATE TABLE DAE_RUOLO
(
   ID            VARCHAR2 (64) NOT NULL,
   NOME          VARCHAR2 (64),
   DESCRIZIONE   VARCHAR2 (64),
   CONSTRAINT PK_DAE_RUOLO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_SCADENZA_DAE
(
   ID               VARCHAR2 (64) NOT NULL,
   DAE              VARCHAR2 (64),
   TIPO_SCADENZA    VARCHAR2 (64),
   DATA_SCADENZA    VARCHAR2 (64),
   STATO_SCADENZA   VARCHAR2 (64),
   CONSTRAINT PK_DAE_SCADENZA_DAE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_SMTP_PROTOCOL_CONFIG
(
   ID                      VARCHAR2 (64) NOT NULL,
   NUMEROPORTA             NUMBER (9),
   HOST                    VARCHAR2 (64),
   ENABLE_AUTHENTICATION   NUMBER (1) DEFAULT 0 NOT NULL,
   ENCRYPTION              VARCHAR2 (64),
   USERNAME                VARCHAR2 (64),
   PASSWORD                VARCHAR2 (64),
   SMTP_DA                 VARCHAR2 (64),
   SMTP_NOME_DA            VARCHAR2 (64),
   SMTP_RISPONDI_A         VARCHAR2 (64),
   CONSTRAINT PK_DAE_SMTP_PROTOCOL_CONFIG_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_RESPONSABILE
(
   ID                    VARCHAR2 (64) NOT NULL,
   DAE                   VARCHAR2 (64),
   NOME                  VARCHAR2 (64),
   COGNOME               VARCHAR2 (64),
   TELEFONO              VARCHAR2 (64),
   DATA_NASCITA          DATE,
   EMAIL                 VARCHAR2 (64),
   INDIRIZZO_RESIDENZA   VARCHAR2 (64),
   --COMUNEDO COMUNERESIDENZA,
   COMUNE_RESIDENZA      VARCHAR2 (64),
   CODICE_FISCALE        VARCHAR2 (64),
   WHATSAPP              NUMBER (1) DEFAULT 0 NOT NULL,
   CONSTRAINT PK_DAE_RESPONSABILE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_COMUNERESIDENZA_ID FOREIGN KEY
      (COMUNE_RESIDENZA)
       REFERENCES DAE_COMUNE (ID)
);

CREATE TABLE DAE_STATO
(
   ID     VARCHAR2 (64) NOT NULL,
   NOME   VARCHAR2 (150),
   CONSTRAINT PK_DAE_STATO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_STATO_RICHIESTA
(
   ID            VARCHAR2 (64) NOT NULL,
   NOME          VARCHAR2 (64),
   DESCRIZIONE   VARCHAR2 (64),
   CONSTRAINT PK_DAE_STATO_RICHIESTA_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_STRUTTURA
(
   ID   VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_DAE_STRUTTURA_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_TIPO_STRUTTURA
(
   ID            VARCHAR2 (64) NOT NULL,
   DESCRIZIONE   VARCHAR2 (64),
   CONSTRAINT PK_DAE_TIPO_STRUTTURA_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_UBICAZIONE
(
   ID            VARCHAR2 (64) NOT NULL,
   TIPO          NUMBER (9),
   DESCRIZIONE   NUMBER (9),
   CONSTRAINT PK_DAE_UBICAZIONE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_USER_DAE_SEERVICES
(
   ID   VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_DAE_USER_DAE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_CERTIFICATO_FR
(
   ID                   VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER      VARCHAR2 (64),
   IMMAGINE             VARCHAR2 (550),
   DATA_CONSEGUIMENTO   DATE DEFAULT (SYSDATE),
   DATA_SCADENZA        DATE DEFAULT (SYSDATE),
   DESCRIZIONE          VARCHAR2 (550),
   RILASCIATO_DA        VARCHAR2 (64),
   EMAIL_SCADENZA       VARCHAR2 (64),
   CONSTRAINT PK_DAE_CERTIFICATO_FR_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_CERTIFICATO_DAE
(
   ID                   VARCHAR2 (64) NOT NULL,
   DAE                  VARCHAR2 (64),
   DATA_CONSEGUIMENTO   DATE DEFAULT (SYSDATE),
   DATA_SCADENZA        DATE DEFAULT (SYSDATE),
   RILASCIATO_DA        VARCHAR2 (64),
   IMMAGINE             VARCHAR2 (64),
   EMAIL_SCADENZA       VARCHAR2 (250),
   DESCRIZIONE          VARCHAR2 (250),
   CONSTRAINT PK_DAE_CERTIFICATO_DAE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_CATEGORIA_FR
(
   ID                         VARCHAR2 (128) NOT NULL,
   DESCRIZIONE                VARCHAR2 (550),
   CHILOMETRI_MINUTO          NUMBER (9),
   ACCETTATI_PER_INTERVENTO   NUMBER (1) DEFAULT 0 NOT NULL,
   ACCETTA_MINUS_KM           NUMBER (9),
   COLORE                     VARCHAR2 (64) NOT NULL,
   CREATA_DA                  VARCHAR2 (64) NOT NULL,
   AGGIORNATA_DA              VARCHAR2 (64) NOT NULL,
   AGGIORNATA_IL              DATE DEFAULT (SYSDATE),
   CONSTRAINT PK_DAE_CATEGORIA_FR_ID PRIMARY KEY (ID)
);

--drop table DAE_FIRST_RESPONDER cascade constraint;

CREATE TABLE DAE_FIRST_RESPONDER
(
   ID                    VARCHAR2 (64) NOT NULL,
   UTENTE                VARCHAR2 (64) NOT NULL,
   NUMERO_CELLULARE      VARCHAR2 (20),
   CATEGORIA_FR          VARCHAR2 (64),
   STATO_PROFILO         VARCHAR2 (128) NOT NULL,
   DATA_ISCRIZIONE       DATE NOT NULL,
   DISPOSITIVI           NUMBER (9),
   -- CERTIFICATOFRDO CERTIFICATEFR,
   CERTIFICATO_FR        VARCHAR2 (64) NOT NULL,
   RICHIESTE_ESEGUITE    NUMBER (9),
   INTERVENTI_ESEGUITI   NUMBER (9),
   CAP                   NUMBER (6),
   --PROFILOSANITARIODO PROFILOSANITARIO,
   PROFILO_SANITARIO     VARCHAR2 (64),
   --LOCATIONDO LASTPOSITION,
   LAST_POSITION         VARCHAR2 (64),
   DISPOSITIVO           VARCHAR2 (512),
   DISPONIBILE           NUMBER DEFAULT 0 NOT NULL,
   PROFESSIONE_ID        VARCHAR2 (64),
   MEDICO_FR             VARCHAR2 (64),
   CONSTRAINT PK_DAE_FIRST_RESPONDER_ID PRIMARY KEY (ID),
   CONSTRAINT FK_UTENTE_ID FOREIGN KEY (UTENTE) REFERENCES DAE_UTENTE (ID),
   CONSTRAINT FK_CATEGORIAFR_ID FOREIGN KEY
      (CATEGORIA_FR)
       REFERENCES DAE_CATEGORIA_FR (ID),
   CONSTRAINT FK_CERTIFICATEFR_ID FOREIGN KEY
      (CERTIFICATO_FR)
       REFERENCES DAE_CERTIFICATO_FR (ID),
   CONSTRAINT FK_FR_LOCATION_ID FOREIGN KEY
      (LAST_POSITION)
       REFERENCES DAE_LOCATION (ID),
   CONSTRAINT FK_PROFESSIONE_ID FOREIGN KEY
      (PROFESSIONE_ID)
       REFERENCES DAE_PROFESSIONE (ID)
);

CREATE TABLE DAE_NOTIFICHE_EVENTI
(
   ID                VARCHAR2 (50 BYTE),
   FIRST_RESPONDER   VARCHAR2 (50 BYTE),
   EVENT             VARCHAR2 (50 BYTE),
   TIME_STAMP        TIMESTAMP,
   CONSTRAINT PK_DAE_NOTIFICHE_EVENTI_ID PRIMARY KEY (ID),
   CONSTRAINT FK_NOTIFICHE_EVENTI_EVENT_ID FOREIGN KEY
      (EVENT)
       REFERENCES DAE_EVENT (ID),
   CONSTRAINT FK_NOTIFICHE_EVENTI_FR_ID FOREIGN KEY
      (FIRST_RESPONDER)
       REFERENCES DAE_FIRST_RESPONDER (ID)
);


CREATE TABLE DAE_MEDICO_FR
(
   ID                      VARCHAR2 (64) NOT NULL,
   NUM_ISCRIZIONE_ORDINE   VARCHAR2 (250),
   DATA_LAUREA             DATE,
   CONSTRAINT PK_DAE_MEDICO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_QUEST_FIRST_RESPONDER
(
   ID                           VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER              VARCHAR2 (64),
   RISP_QUEST_FIRST_RESPONDER   VARCHAR2 (64),
   DELETED                      NUMBER (1) DEFAULT 0 NOT NULL,
   CONSTRAINT PK_DAE_QUEST_FIRST_RESP_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DOM_QUEST_FR_ID FOREIGN KEY
      (FIRST_RESPONDER)
       REFERENCES DAE_FIRST_RESPONDER (ID),
   CONSTRAINT FK_RISP_QUEST_FR_ID FOREIGN KEY
      (RISP_QUEST_FIRST_RESPONDER)
       REFERENCES DAE_RISP_QUEST_FIRST_RESPONDER (ID)
);

CREATE TABLE DAE_STATO_DAE
(
   ID          VARCHAR2 (64) NOT NULL,
   DAE         VARCHAR2 (64),
   STATO       VARCHAR2 (64),
   VALIDO_DA   DATE,
   VALIDO_A    DATE,
   CONSTRAINT PK_DAE_STATO_DAE_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_DAE
(
   ID                          VARCHAR2 (64) NOT NULL,
   OPERATIVO                   NUMBER (1) DEFAULT 0 NOT NULL,
   MATRICOLA                   VARCHAR2 (64),
   MODELLO                     VARCHAR2 (64),
   TIPO                        VARCHAR2 (64),
   ALIAS                       VARCHAR2 (64),
   DATA_INSERIMENTO            DATE,
   TIMESTAMPE_INSERIMENTO      TIMESTAMP,
   --TIPOSTRUTTURA TIPOLOGIASTRUTTURA
   TIPOLOGIA_STRUTTURA         VARCHAR2 (64) NOT NULL,
   NOMESEDE                    VARCHAR2 (64),
   --RESPONSABILE RESPONSABILE
   RESPONSABILE                VARCHAR2 (64) NOT NULL,
   UBICAZIONE                  VARCHAR2 (64),
   NOTE_DI_ACCESSO_ALLA_SEDE   VARCHAR2 (64),
   --LOCATION POSIZIONE
   POSIZIONE                   VARCHAR2 (64) NOT NULL,
   --IMAGE IMMAGINE
   IMMAGINE                    VARCHAR2 (64),
   --DISPONIBILITA[] DISPONIBILITA
   CERTIFICATO_DAE             VARCHAR2 (64),
   SCADENZA_DAE                DATE,
   --PROGRAMMAMANUTENZIONE[] PROGRAMMAMANUTENZIONE
   NOTE_GENERALI               VARCHAR2 (64),
   STATO_VALIDAZIONE           VARCHAR2 (15),
   CURRENT_STATO_ID            VARCHAR2 (64),
   --STATODAE[] STATODAE
   --STATODAE VARCHAR2(64) NOT NULL,
   CONSTRAINT PK_DAE_DAE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_TIPOLOGIASTRUTTURA_DAE_ID FOREIGN KEY
      (TIPOLOGIA_STRUTTURA)
       REFERENCES DAE_TIPO_STRUTTURA (ID),
   CONSTRAINT FK_POSIZIONE_DAE_ID FOREIGN KEY
      (POSIZIONE)
       REFERENCES DAE_LOCATION (ID),
   CONSTRAINT FK_IMMAGINE_DAE_ID FOREIGN KEY
      (IMMAGINE)
       REFERENCES DAE_IMAGE (ID),
   CONSTRAINT FK_RESPONSABILE_DAE_ID FOREIGN KEY
      (RESPONSABILE)
       REFERENCES DAE_RESPONSABILE (ID),
   CONSTRAINT FK_CERTIFICATO_DAE_ID FOREIGN KEY
      (CERTIFICATO_DAE)
       REFERENCES DAE_CERTIFICATO_DAE (ID)
);

CREATE TABLE DAE_PROGRAMMA_MANUTENZIONE
(
   ID                        VARCHAR2 (64) NOT NULL,
   DAE                       VARCHAR2 (64) NOT NULL,
   INTERVALLOTRAINTERVENTI   NUMBER (9),
   DURATA                    NUMBER (9),
   SCADENZADOPO              DATE,
   -- MANUTENTOREDO RESPONSABILE,
   MANUTENTORE               VARCHAR2 (64),
   STATO                     VARCHAR2 (64),
   NOTA                      VARCHAR2 (64),
   TIPOMANUTENZIONE          VARCHAR2 (64),
   MAIL_ALERT                VARCHAR2 (64),
   CONSTRAINT PK_DAE_PRG_MANUTENZIONE_ID PRIMARY KEY (ID),
   CONSTRAINT FK_PRG_MANUTENZIONE_DAE_ID FOREIGN KEY
      (DAE)
       REFERENCES DAE_DAE (ID),
   CONSTRAINT FK_MANUTENTORE_ID FOREIGN KEY
      (MANUTENTORE)
       REFERENCES DAE_MANUTENTORE (ID)
);

CREATE TABLE DAE_DISPONIBILITA
(
   ID                       VARCHAR2 (64) NOT NULL,
   DAE                      VARCHAR2 (64) NOT NULL,
   DISPONIBILTA_SPECIFICA   VARCHAR2 (64),
   DELETED                  NUMBER (1) DEFAULT 0 NOT NULL,
   DA                       DATE,
   A                        DATE,
   ORARIO_DA                VARCHAR2 (5),
   ORARIO_A                 VARCHAR2 (5),
   CONSTRAINT DAE_DISPONIBILITA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DAE_DISPONIBILITA_DAE_ID FOREIGN KEY
      (DAE)
       REFERENCES DAE_DAE (ID)
);

CREATE TABLE DAE_DISPONIBILITA_ECCEZIONI
(
   ID              VARCHAR2 (64) NOT NULL,
   DISPONIBILITA   VARCHAR2 (64) NOT NULL,
   DATA            DATE,
   MOTIVAZIONE     VARCHAR2 (250),
   CONSTRAINT DAE_DISPONIBILITA_ECCEZIONI_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DISPONIBILITA_ECCEZIONI_ID FOREIGN KEY
      (DISPONIBILITA)
       REFERENCES DAE_DISPONIBILITA (ID)
);

CREATE TABLE DAE_DISPONIBILITA_SPECIFICA
(
   ID              VARCHAR2 (64) NOT NULL,
   DISPONIBILITA   VARCHAR2 (64) NOT NULL,
   CONSTRAINT DAE_DISPONIBILITA_SPECIFICA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DISPONIBILITA_SPEC_ID FOREIGN KEY
      (DISPONIBILITA)
       REFERENCES DAE_DISPONIBILITA (ID)
);

CREATE TABLE DAE_DISPONIBILITA_GIORNALIERA
(
   ID                        VARCHAR2 (64) NOT NULL,
   DISPONIBILITA_SPECIFICA   VARCHAR2 (64) NOT NULL,
   ORARIO_DA                 VARCHAR2 (5),
   ORARIO_A                  VARCHAR2 (5),
   GIORNO_SETTIMANA          VARCHAR2 (25),
   CONSTRAINT PK_DISP_GIORNALIERA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DISP_SPECIFICA_ID FOREIGN KEY
      (DISPONIBILITA_SPECIFICA)
       REFERENCES DAE_DISPONIBILITA_SPECIFICA (ID)
);

CREATE TABLE DAE_INTERVENTO
(
   ID                  VARCHAR2 (64) NOT NULL,
   EVENT_ID            VARCHAR2 (512) NOT NULL,
   DATA_CREAZIONE      TIMESTAMP NOT NULL,
   DATA_ACCETTAZIONE   TIMESTAMP,
   DATA_RIFIUTO        TIMESTAMP,
   DATA_ANNULLAMENTO   TIMESTAMP,
   ACCETTATO_DA        VARCHAR2 (64),
   RIFIUTATO_DA        VARCHAR2 (64),
   ANNULLATO_DA        VARCHAR2 (64),
   DURATA              NUMBER (9),
   OSSERVAZIONE        VARCHAR2 (900),
   CONSTRAINT PK_DAE_INTERVENTO_ID PRIMARY KEY (ID)
);

CREATE TABLE DAE_RICHIESTA
(
   ID                   VARCHAR2 (64),
   CODICE_RICHIESTA     NUMBER (9),
   DATA                 DATE,
   --GPSLOCATIONDO LUOGO,
   LUOGO                VARCHAR2 (64) NOT NULL,
   NOTA                 VARCHAR2 (64),
   --FIRSTRESPONDERDO APERTODA,
   APERTO_DA            VARCHAR2 (64),
   --STATORICHIESTADO STATORICHIESTA,
   STATO_RICHIESTA      VARCHAR2 (64),
   --PROVINCIADO[] INVIAALERTA,
   INVIA_ALERT_A        VARCHAR2 (64),
   TEMPO_MINIMO_ALERT   NUMBER (9),
   CONSTRAINT PK_DAE_RICHIESTA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_APERTODA_ID FOREIGN KEY
      (APERTO_DA)
       REFERENCES DAE_UTENTE (ID),
   CONSTRAINT FK_STATORICHIESTA_ID FOREIGN KEY
      (STATO_RICHIESTA)
       REFERENCES DAE_STATO_RICHIESTA (ID),
   CONSTRAINT FK_INVIAALERTA_ID FOREIGN KEY
      (INVIA_ALERT_A)
       REFERENCES DAE_PROVINCIA (ID)
);

CREATE TABLE DAE_GRUPPO_FIRST_RESPONDER
(
   GRUPPO            VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER   VARCHAR2 (64) NOT NULL,
   PRIMARY KEY (FIRST_RESPONDER, GRUPPO),
   CONSTRAINT fk_FIRST_RESPONDER_GRUPPO FOREIGN KEY
      (FIRST_RESPONDER)
       REFERENCES DAE_FIRST_RESPONDER (ID),
   CONSTRAINT fk_GRUPPO_FIRST_RESPONDER FOREIGN KEY
      (GRUPPO)
       REFERENCES DAE_GRUPPO (ID)
);

CREATE TABLE DAE_DISPOSITIVI
(
   ID                VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER   VARCHAR2 (64),
   MARCA             VARCHAR2 (150),
   MODELLO           VARCHAR2 (150),
   OS                VARCHAR2 (64),
   PUSH_TOKEN        VARCHAR2 (512),
   ULTIMO_ACCESSO    DATE,
   DEVICE_ID         VARCHAR2 (512),
   CONSTRAINT PK_DAE_DISPOSITIVI_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DISPO_FIRST_RESPONDER_ID FOREIGN KEY
      (FIRST_RESPONDER)
       REFERENCES DAE_FIRST_RESPONDER (ID)
);

CREATE TABLE DAE_MOBILE_TOKEN
(
   TOKEN                VARCHAR2 (128 BYTE),
   CREATION_TIMESTAMP   TIMESTAMP,
   UTENTE_ID            VARCHAR2 (64 BYTE),
   RENEWED_TIMESTAMP    TIMESTAMP,
   EXPIRED_TIMESTAMP    TIMESTAMP,
   FIRST_RESPONDER_ID   VARCHAR2 (128 BYTE)
);

CREATE TABLE DAE_UTENTE_RUOLO
(
   UTENTE_ID   VARCHAR2 (64) NOT NULL,
   RUOLO_ID    VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_DAE_UTENTE_RUOLO PRIMARY KEY (UTENTE_ID, RUOLO_ID)
);

CREATE TABLE DAE_RESET_PASSWORD
(
   ID               VARCHAR2 (64) NOT NULL,
   UTENTE_ID        VARCHAR2 (64) NOT NULL,
   TOKEN            VARCHAR2 (512),
   IP               VARCHAR2 (64),
   STATO            VARCHAR2 (12),
   DATA_RICHIESTA   DATE,
   CONSTRAINT PK_RESET_PASSWORD_ID PRIMARY KEY (ID),
   CONSTRAINT FK_RESET_PASSWORD_UTENTE_ID FOREIGN KEY
      (UTENTE_ID)
       REFERENCES DAE_UTENTE (ID)
);

CREATE TABLE DAE_UTENTE_GRUPPO
(
   UTENTE_ID   VARCHAR2 (64),
   GRUPPO_ID   VARCHAR2 (64)
);

ALTER TABLE DAE_UTENTE_GRUPPO ADD (
  CONSTRAINT DAE_UTENTE_GRUPPO_PK
  PRIMARY KEY
  (UTENTE_ID, GRUPPO_ID)  );

ALTER TABLE DAE_UTENTE_GRUPPO ADD (
  CONSTRAINT DAE_UTENTE_GRUPPO_R01
  FOREIGN KEY (UTENTE_ID)
  REFERENCES DAE_UTENTE (ID)  ,
  CONSTRAINT DAE_UTENTE_GRUPPO_R02
  FOREIGN KEY (GRUPPO_ID)
  REFERENCES DAE_GRUPPO (ID)
  );

CREATE TABLE DAE_PASSWORD_HISTORY
(
   ID              VARCHAR2 (64) NOT NULL,
   UTENTE_ID       VARCHAR2 (64) NOT NULL,
   CREATION_DATE   DATE,
   PASSWORD_HASH   VARCHAR2 (1024),
   TEMPORANY       NUMBER,
   CONSTRAINT PK_PASSWORD_HISTORY_ID PRIMARY KEY (ID),
   CONSTRAINT FK_PASSWORD_HISTORY_UTENTE_ID FOREIGN KEY
      (UTENTE_ID)
       REFERENCES DAE_UTENTE (ID)
);

CREATE TABLE DAE_GRUPPO_PROVINCIA
(
   ID               VARCHAR2 (64) NOT NULL,
   GRUPPO_ID        VARCHAR2 (64) NOT NULL,
   NOME_PROVINCIA   VARCHAR2 (64),
   CONSTRAINT PK_GRUPPO_PROVINCIA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_GRUPPO_PROVINCIA_GRUPPO_ID FOREIGN KEY
      (GRUPPO_ID)
       REFERENCES DAE_GRUPPO (ID)
);

CREATE TABLE DAE_INTERVENTO_COORD
(
   ID              VARCHAR2 (64) NOT NULL,
   TS_COORDINATA   TIMESTAMP NOT NULL,
   INTERVENTO_ID   VARCHAR2 (64) NOT NULL,
   LATITUDINE      VARCHAR2 (64) NOT NULL,
   LONGITUDINE     VARCHAR2 (64) NOT NULL
);

CREATE TABLE DAE_DAE_FAULT
(
   ID                  VARCHAR2 (64) NOT NULL,
   DAE_ID              VARCHAR2 (64) NOT NULL,
   UTENTE_ID           VARCHAR2 (64) NOT NULL,
   TIPOLOGIA           VARCHAR2 (64),
   NOTE                VARCHAR2 (1024),
   DATA_SEGNALAZIONE   TIMESTAMP NOT NULL,
   STATO_ATTUALE       VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_DAE_DAE_FAULT_ID PRIMARY KEY (ID),
   CONSTRAINT FK_DAE_DAE_FAULT_DAE_ID FOREIGN KEY
      (DAE_ID)
       REFERENCES DAE_DAE (ID),
   CONSTRAINT FK_DAE_DAE_FAULT_UTENTE_ID FOREIGN KEY
      (UTENTE_ID)
       REFERENCES DAE_UTENTE (ID)
);

CREATE TABLE DAE_COMUNE_COMPETENZA
(
   FIRST_RESPONDER_ID   VARCHAR2 (64) NOT NULL,
   COMUNE_ID            VARCHAR2 (64) NOT NULL,
   CONSTRAINT PK_COMUNE_COMPETENZA_ID PRIMARY KEY (FIRST_RESPONDER_ID, COMUNE_ID)
);


CREATE TABLE DAE_FR_POSITION_TO_CO
(
   ID                   VARCHAR2 (64) NOT NULL,
   FIRST_RESPONDER_ID   VARCHAR2 (64),
   LATITUDINE           NUMBER,
   LONGITUDINE          NUMBER,
   TIME_STAMP           DATE,
   CONSTRAINT PK_DAE_FR_POS_ID PRIMARY KEY (ID)
);