/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorityFilterDTO { 
    type?: string;
    fetchRule?: string;
    compact?: string;
    description?: string;
    costCenter?: string;
    convention?: string;
    withPhone?: boolean;
    exactValue?: boolean;
    id?: string;
}
