
CREATE SEQUENCE GUID AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE TABLE DUAL (GUID integer NOT NULL);



CREATE TABLE "TS_BOOKING_ID" 
   (	
    "YEAR" integer, 
	"BOOKING_ID" integer
   )
  ;


CREATE TABLE "TO_BOOKING" 
   (	"ID" VARCHAR(28) NOT NULL , 
	"CODE" VARCHAR(16) NOT NULL , 
	"CREATION_DATE" DATE NOT NULL , 
	"CREATED_BY" VARCHAR(64) NOT NULL , 
	"MODIFIED_BY" VARCHAR(64), 
	"AUTHORITY_ID1" VARCHAR(28), 
	"AUTHORITY_ID2" VARCHAR(28), 
	"DEPARTMENT_ID1" VARCHAR(28), 
	"DEPARTMENT_ID2" VARCHAR(28), 
	"TRANSPORT_DATE" DATE NOT NULL , 
	"DATE_FLAG" integer, 
	"RESCUE_DATE" DATE, 
	"ARRIVE_DATE" DATE, 
	"RESOURCE_ID" VARCHAR(28), 
	"RETURN_DATE" DATE, 
	"PRIORITY" VARCHAR(2), 
	"COMPACT_ADDRESS" VARCHAR(200), 
	"STREET_NAME" VARCHAR(70), 
	"HOUSE_NUMBER" VARCHAR(12), 
	"MUNICIPALITY" VARCHAR(50), 
	"LOCALITY" VARCHAR(50), 
	"PROVINCE" VARCHAR(35), 
	"COMPACT_ADDRESS2" VARCHAR(200), 
	"STREET_NAME2" VARCHAR(70), 
	"HOUSE_NUMBER2" VARCHAR(12), 
	"MUNICIPALITY2" VARCHAR(50), 
	"LOCALITY2" VARCHAR(50), 
	"PROVINCE2" VARCHAR(35), 
	"TRANSPORT_TYPE" VARCHAR(20), 
	"PAT_STATUS" VARCHAR(20), 
	"COMPANION" VARCHAR(20), 
	"REQ_TYPE" VARCHAR(20), 
	"REQ_CONVENTION" VARCHAR(20), 
	"REQ_DESCR" VARCHAR(64), 
	"REQ_DETAIL" VARCHAR(64), 
	"REQ_REF" VARCHAR(64), 
	"REQ_VAT" VARCHAR(16), 
	"REQ_CC" VARCHAR(16), 
	"START_AUTHORITY_ID" VARCHAR(28), 
	"START_DEPARTMENT_ID" VARCHAR(28), 
	"START_TYPE" VARCHAR(20), 
	"START_CONVENTION" VARCHAR(20), 
	"START_DESCR" VARCHAR(64), 
	"START_DETAIL" VARCHAR(64), 
	"START_REFERENCE" VARCHAR(64), 
	"START_VAT" VARCHAR(16), 
	"START_CC" VARCHAR(16), 
	"DEST_TYPE" VARCHAR(20), 
	"DEST_CONVENTION" VARCHAR(20), 
	"DEST_DESCR" VARCHAR(64), 
	"DEST_DETAIL" VARCHAR(64), 
	"DEST_REFERENCE" VARCHAR(64), 
	"DEST_VAT" VARCHAR(16), 
	"DEST_CC" VARCHAR(16), 
	"ORGANS_FLAG" integer, 
	"BLOOD" integer, 
	"VARIOUS_DETAIL" VARCHAR(64), 
	"STATUS" VARCHAR(2), 
	"DELETE_SYS_DATE" DATE, 
	"DELETE_USR_NAME" VARCHAR(64), 
	"DELETE_REASON" VARCHAR(64), 
	"BOOKING_ID" VARCHAR(28), 
	"RETURN_READY" integer, 
	"CICLICAL_ID" VARCHAR(28), 
	"MEDICAL_REQUEST" integer, 
	"MEDICAL_AUTHORIZATION" integer, 
	"DOCTOR_ID" VARCHAR(28), 
	"DOCTOR_NAME" VARCHAR(128), 
	"DOCTOR_COST_CENTER" VARCHAR(16), 
	"PROTECT_RESOURCE_REQUEST" integer, 
	"RESOURCE_TYPE" VARCHAR(35), 
	"OPTIONED_PARKING_ID" VARCHAR(28), 
	"OPTIONED_PARKING" VARCHAR(16), 
	"ASSIGNED_PARKING_ID" VARCHAR(28), 
	"ASSIGNED_PARKING" VARCHAR(16), 
	"HISTORY_FLAG" integer, 
	"SPECIAL_EQUIPMENT_FLAG" integer, 
	"NOTE" VARCHAR(1024), 
	"WEB_BOOKING_ID" VARCHAR(28), 
	"START_TELEPHONE" VARCHAR(50), 
	"DEST_TELEPHONE" VARCHAR(50), 
	"REQ_TELEPHONE" VARCHAR(50), 
	"CATEGORY" VARCHAR(64), 
	"START_PAVILION_NUMBER" VARCHAR(16), 
	"START_PAVILION_NAME" VARCHAR(64), 
	"END_PAVILION_NUMBER" VARCHAR(16), 
	"END_PAVILION_NAME" VARCHAR(64), 
	"CHARGE" VARCHAR(10), 
	"CALLER_TELEPHONE" VARCHAR(50), 
	"CALLER_SOURCE" VARCHAR(64), 
	"INDICATIONS" VARCHAR(1024), 
	"MANUTENCOOP_SEND_STATUS" VARCHAR(1), 
	"EPISODE_RECOVERY_PS" VARCHAR(50), 
	"WEB_TARGET_EMERGENCY_ID" VARCHAR(16), 
	"WEB_SENDING_USR_NAME" VARCHAR(16), 
	"WEB_SENDING_USR_DATE" DATE
	);
	
	CREATE TABLE "TO_BOOKING_PATIENT" 
   (	
    "ID" VARCHAR(28) NOT NULL , 
	"BOOKING_ID" VARCHAR(28) NOT NULL , 
	"TYPE" VARCHAR(32), 
	"SURNAME" VARCHAR(64), 
	"NAME" VARCHAR(64), 
	"BIRTH_DATE" DATE, 
	"BIRTH_PLACE" varchar(64),
	"TAX_CODE" VARCHAR(16), 
	"SANITARY_CODE" VARCHAR(16), 
	"SEX" VARCHAR(1), 
	"FIRST_TELEPHONE" VARCHAR(50), 
	"SECOND_TELEPHONE" VARCHAR(50), 
	"TICKET" integer, 
	"STREET_NAME" VARCHAR(70), 
	"HOUSE_NUMBER" VARCHAR(12), 
	"LOCALITY" VARCHAR(50), 
	"MUNICIPALITY" VARCHAR(50), 
	"PROVINCE" VARCHAR(35), 
	"ACCESSIBILITY" VARCHAR(64), 
	"ADDITIONAL_PATIENT_ID" VARCHAR(28)
	
	);
	
	CREATE TABLE "TS_BOOKING_EQUIPMENT" 
   (
   	"ID" VARCHAR(28) NOT NULL, 
	"BOOKING_ID" VARCHAR(28) NOT NULL, 
	"EQUIPMENT_ID" VARCHAR(28) NOT NULL
	);
	
   CREATE TABLE "TS_EQUIPMENT" (
	 "ID" VARCHAR(28) NOT NULL, 
	"COMPACT" VARCHAR(20) NOT NULL, 
	"DESCRIPTION" VARCHAR(64) NOT NULL, 
	"SELECTED" integer, 
	"WEB_VISIBLE" integer, 
	"TYPE" VARCHAR(28)
	);
	
	CREATE TABLE "WEB_IDENTITY" 
   (	"ID" VARCHAR(28) NOT NULL, 
	"TABLE_TYPE" VARCHAR(64), 
	"TABLE_ID" VARCHAR(28), 
	"DESCRIPTION" VARCHAR(128), 
	"LOGIN" VARCHAR(64), 
	"PASSWD" VARCHAR(64), 
	"EMAIL" VARCHAR(64), 
	"TYPE" VARCHAR(50),
	"PASSWORD_MODIFY_DATE" DATE
	);
	
--	ALTER TABLE WEB_IDENTITY ADD (PASSWORD_MODIFY_DATE DATE );
	
	CREATE TABLE "WEB_SESSIONS" 
   (	"ID" VARCHAR(28) NOT NULL, 
	"WEB_IDENTITY_ID" VARCHAR(28) NOT NULL, 
	"LOGIN_TIMESTAMP" DATE, 
	"ADDRESS" VARCHAR(64), 
	"SESSION_ID" VARCHAR(64)
	);
	
	
  CREATE TABLE "WEB_BOOKING" 
   (	"ID" VARCHAR(28) NOT NULL,  
	"CREATION_DATE" DATE NOT NULL,  
	"TRANSPORT_DATE" DATE, 
	"TRANSPORT_TYPE" VARCHAR(20), 
	"PAT_STATUS" VARCHAR(20), 
	"SURNAME" VARCHAR(64), 
	"NAME" VARCHAR(64), 
	"SANITARY_CODE" VARCHAR(16), 
	"TAX_CODE" VARCHAR(16), 
	"START_DESCR" VARCHAR(64), 
	"START_DETAIL" VARCHAR(64), 
	"START_STREET_NAME" VARCHAR(70), 
	"START_HOUSE_NUMBER" VARCHAR(12), 
	"START_LOCALITY" VARCHAR(50), 
	"START_MUNICIPALITY" VARCHAR(50), 
	"START_PROVINCE" VARCHAR(35), 
	"DEST_DESCR" VARCHAR(64), 
	"DEST_DETAIL" VARCHAR(64), 
	"DEST_STREET_NAME" VARCHAR(70), 
	"DEST_HOUSE_NUMBER" VARCHAR(12), 
	"DEST_LOCALITY" VARCHAR(50), 
	"DEST_MUNICIPALITY" VARCHAR(50), 
	"DEST_PROVINCE" VARCHAR(35), 
	"REQ_DESCR" VARCHAR(64), 
	"REQ_DETAIL" VARCHAR(64), 
	"OPTIONED_PARKING" VARCHAR(16), 
	"STATUS" VARCHAR(2), 
	"STATUS_REASON" VARCHAR(20), 
	"DUPLICATED_ID" VARCHAR(28), 
	"NOTE" VARCHAR(256), 
	"PATIENT_COMPANION" VARCHAR(20), 
	"PATIENT_CHARGEABLE" integer, 
	"START_TELEPHONE" VARCHAR(50), 
	"DEST_TELEPHONE" VARCHAR(50), 
	"REQ_TELEPHONE" VARCHAR(50), 
	"DATE_FLAG" integer, 
	"PATIENT_TELEPHONE" VARCHAR(50), 
	"FLOOR_PART_NUMBER" VARCHAR(4), 
	"FLOOR_DEST_NUMBER" VARCHAR(4), 
	"LIFT_PART" VARCHAR(2), 
	"LIFT_DEST" VARCHAR(2), 
	"REFERENCE" VARCHAR(80), 
	"ID_EXTERNAL_REF" VARCHAR(64), 
	"CODE" VARCHAR(64)
   ) 
 ;
 
  -- CREATE UNIQUE INDEX "PK_WEB_BOOKING" ON "WEB_BOOKING" ("ID");
  -- ALTER TABLE "WEB_BOOKING" MODIFY ("ID" NOT NULL ENABLE); 
  -- ALTER TABLE "WEB_BOOKING" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 	
   CREATE TABLE "WEB_BOOKING_EQUIPMENT" 
   (	
    "ID" VARCHAR(28) NOT NULL , 
	"WEB_BOOKING_ID" VARCHAR(28) NOT NULL , 
	"EQUIPMENT_ID" VARCHAR(28), 
	"EQUIPMENT_COMPACT" VARCHAR(20), 
	 CONSTRAINT "PK_WEB_BOOKING_EQUIPMENT" PRIMARY KEY ("ID")
   ) ;
	