/* Formatted on 18/11/2016 12:36:24 (QP5 v5.115.810.9015) */
DELETE   DAE_CATEGORIA_FR;

DELETE   dae_comune;

DELETE   dae_provincia;

INSERT INTO DAE_CATEGORIA_FR (ID,
                              DESCRIZIONE,
                              CHILOMETRI_MINUTO,
                              ACCETTATI_PER_INTERVENTO,
                              ACCETTA_MINUS_KM,
                              COLORE,
                              --MAPPA,
                              CREATA_DA,
                              AGGIORNATA_DA,
                              AGGIORNATA_IL)
  VALUES   ('FIRST_RESPONDER',
            'First Responder',
            '99',
            '1',
            '10',
            '123',
            --NULL,
            ' ',
            ' ',
            TO_DATE ('14-NOV-16', 'DD-MON-RR'));

INSERT INTO DAE_CATEGORIA_FR (ID,
                              DESCRIZIONE,
                              CHILOMETRI_MINUTO,
                              ACCETTATI_PER_INTERVENTO,
                              ACCETTA_MINUS_KM,
                              COLORE,
                              --MAPPA,
                              CREATA_DA,
                              AGGIORNATA_DA,
                              AGGIORNATA_IL)
  VALUES   ('LUCI_BLU',
            'Luci Blu',
            '1',
            '6',
            '5',
            'BLU',
            --NULL,
            ' ',
            ' ',
            TO_DATE ('14-NOV-16', 'DD-MON-RR'));

INSERT INTO DAE_CATEGORIA_FR (ID,
                              DESCRIZIONE,
                              CHILOMETRI_MINUTO,
                              ACCETTATI_PER_INTERVENTO,
                              ACCETTA_MINUS_KM,
                              COLORE,
                              --MAPPA,
                              CREATA_DA,
                              AGGIORNATA_DA,
                              AGGIORNATA_IL)
  VALUES   ('RAPID_RESPONDER',
            'Rapid Responder',
            '1',
            '6',
            '10',
            'RED',
            --NULL,
            ' ',
            ' ',
            TO_DATE ('14-NOV-16', 'DD-MON-RR'));

INSERT INTO DAE_CATEGORIA_FR (ID,
                              DESCRIZIONE,
                              CHILOMETRI_MINUTO,
                              ACCETTATI_PER_INTERVENTO,
                              ACCETTA_MINUS_KM,
                              COLORE,
                              -- MAPPA,
                              CREATA_DA,
                              AGGIORNATA_DA,
                              AGGIORNATA_IL)
  VALUES   ('SUPER_USER',
            'Super User',
            '100',
            '6',
            '200',
            'VIOLET',
            -- NULL,
            ' ',
            ' ',
            TO_DATE ('14-NOV-16', 'DD-MON-RR'));

CREATE TABLE province_istat
(
   codice_istat   VARCHAR2 (3),
   nome           VARCHAR2 (64),
   sigla          VARCHAR2 (2)
);

SET DEFINE OFF;

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('001', 'TORINO', 'TO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('002', 'VERCELLI', 'VC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('003', 'NOVARA', 'NO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('004', 'CUNEO', 'CN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('005', 'ASTI', 'AT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('006', 'ALESSANDRIA', 'AL');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('096', 'BIELLA', 'BI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('103', 'VERBANO-CUSIO-OSSOLA', 'VB');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('007', 'VALLE D''AOSTA/VALL�E D''AOSTE', 'AO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('012', 'VARESE', 'VA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('013', 'COMO', 'CO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('014', 'SONDRIO', 'SO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('015', 'MILANO', 'MI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('016', 'BERGAMO', 'BG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('017', 'BRESCIA', 'BS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('018', 'PAVIA', 'PV');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('019', 'CREMONA', 'CR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('020', 'MANTOVA', 'MN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('097', 'LECCO', 'LC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('098', 'LODI', 'LO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('108', 'MONZA E DELLA BRIANZA', 'MB');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('021', 'BOLZANO/BOZEN', 'BZ');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('022', 'TRENTO', 'TN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('023', 'VERONA', 'VR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('024', 'VICENZA', 'VI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('025', 'BELLUNO', 'BL');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('026', 'TREVISO', 'TV');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('027', 'VENEZIA', 'VE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('028', 'PADOVA', 'PD');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('029', 'ROVIGO', 'RO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('030', 'UDINE', 'UD');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('031', 'GORIZIA', 'GO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('032', 'TRIESTE', 'TS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('093', 'PORDENONE', 'PN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('008', 'IMPERIA', 'IM');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('009', 'SAVONA', 'SV');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('010', 'GENOVA', 'GE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('011', 'LA SPEZIA', 'SP');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('033', 'PIACENZA', 'PC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('034', 'PARMA', 'PR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('035', 'REGGIO NELL''EMILIA', 'RE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('036', 'MODENA', 'MO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('037', 'BOLOGNA', 'BO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('038', 'FERRARA', 'FE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('039', 'RAVENNA', 'RA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('040', 'FORL�-CESENA', 'FC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('099', 'RIMINI', 'RN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('045', 'MASSA-CARRARA', 'MS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('046', 'LUCCA', 'LU');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('047', 'PISTOIA', 'PT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('048', 'FIRENZE', 'FI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('049', 'LIVORNO', 'LI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('050', 'PISA', 'PI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('051', 'AREZZO', 'AR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('052', 'SIENA', 'SI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('053', 'GROSSETO', 'GR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('100', 'PRATO', 'PO');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('054', 'PERUGIA', 'PG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('055', 'TERNI', 'TR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('041', 'PESARO E URBINO', 'PU');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('042', 'ANCONA', 'AN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('043', 'MACERATA', 'MC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('044', 'ASCOLI PICENO', 'AP');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('109', 'FERMO', 'FM');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('056', 'VITERBO', 'VT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('057', 'RIETI', 'RI');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('058', 'ROMA', 'RM');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('059', 'LATINA', 'LT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('060', 'FROSINONE', 'FR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('066', 'L''AQUILA', 'AQ');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('067', 'TERAMO', 'TE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('068', 'PESCARA', 'PE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('069', 'CHIETI', 'CH');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('070', 'CAMPOBASSO', 'CB');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('094', 'ISERNIA', 'IS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('061', 'CASERTA', 'CE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('062', 'BENEVENTO', 'BN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('063', 'NAPOLI', 'NA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('064', 'AVELLINO', 'AV');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('065', 'SALERNO', 'SA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('071', 'FOGGIA', 'FG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('072', 'BARI', 'BA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('073', 'TARANTO', 'TA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('074', 'BRINDISI', 'BR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('075', 'LECCE', 'LE');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('110', 'BARLETTA-ANDRIA-TRANI', 'BT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('076', 'POTENZA', 'PZ');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('077', 'MATERA', 'MT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('078', 'COSENZA', 'CS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('079', 'CATANZARO', 'CZ');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('080', 'REGGIO DI CALABRIA', 'RC');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('101', 'CROTONE', 'KR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('102', 'VIBO VALENTIA', 'VV');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('081', 'TRAPANI', 'TP');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('082', 'PALERMO', 'PA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('083', 'MESSINA', 'ME');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('084', 'AGRIGENTO', 'AG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('085', 'CALTANISSETTA', 'CL');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('086', 'ENNA', 'EN');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('087', 'CATANIA', 'CT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('088', 'RAGUSA', 'RG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('089', 'SIRACUSA', 'SR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('090', 'SASSARI', 'SS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('091', 'NUORO', 'NU');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('092', 'CAGLIARI', 'CA');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('095', 'ORISTANO', 'OR');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('104', 'OLBIA-TEMPIO', 'OT');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('105', 'OGLIASTRA', 'OG');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('106', 'MEDIO CAMPIDANO', 'VS');

INSERT INTO PROVINCE_ISTAT (CODICE_ISTAT, NOME, SIGLA)
  VALUES   ('107', 'CARBONIA-IGLESIAS', 'CI');

INSERT INTO DAE_PROVINCIA
   (SELECT   a.ID,
             b.nome,
             b.codice_istat,
             a.name
      FROM   web118_clu.PROVINCE a, province_istat b
     WHERE   (a.DELETED = '0' OR a.DELETED IS NULL) AND A.NAME = B.SIGLA(+));

DROP TABLE province_istat;

INSERT INTO DAE_COMUNE
   (SELECT   ID,
             NAME,
             PROVINCE_ID,
             ISTAT_CODE
      FROM   web118_clu.MUNICIPALITY
     WHERE   DELETED = '0' OR DELETED IS NULL);

COMMIT;





INSERT INTO DAE_CONFIG VALUES ('USER_PROXY','USE_PROXY','TRUE');
INSERT INTO DAE_CONFIG VALUES ('PUSH_NOTIFICATION_ENABLED','PUSH_NOTIFICATION_ENABLED','FALSE');
INSERT INTO DAE_CONFIG VALUES ('PROXY_ADDRESS','PROXY_ADDRESS','proxy.eng.it');
INSERT INTO DAE_CONFIG VALUES ('PROXY_PORT','PROXY_PORT','3128');
INSERT INTO DAE_CONFIG VALUES ('PROXY_USERNAME','PROXY_USERNAME','marmastr');
INSERT INTO DAE_CONFIG VALUES ('PROXY_PASSWORD','PROXY_PASSWORD','12345678');
INSERT INTO DAE_CONFIG VALUES ('PUSHWOOSH_URL','PUSHWOOSH_URL','https://cp.pushwoosh.com/json/1.3/createMessage');
INSERT INTO DAE_CONFIG VALUES ('PUSH_APPLICATION','PUSH_APPLICATION','B719A-01522');
INSERT INTO DAE_CONFIG  VALUES('PUSH_AUTH','PUSH_AUTH','1N7OCff0vAeZISXEvpdmG99TTLlDCU5FFzCuo3jJSRiQbqdRFpwlCgvivMz4TcBoikP2puKwznBAZ5fgSoIg');
INSERT INTO DAE_CONFIG  VALUES('DISTANCE_THRESHOLD','DISTANCE_THRESHOLD','50');

INSERT INTO DAE_CONFIG  VALUES('NEW_USER_MAIL_TEMPLATE','NEW_USER_MAIL_TEMPLATE','Benvenuto {nome} {congome}, residente in {indirizzo},{comune}. Grazie per esserti registrato al sistema');
INSERT INTO DAE_CONFIG  VALUES('ENABLE_MAIL','ENABLE_MAIL','FALSE');
INSERT INTO DAE_CONFIG  VALUES('ENABLE_POSTGIS_SAVE','ENABLE_POSTGIS_SAVE','FALSE');








COMMIT;


