  CREATE TABLE "WEB118_CLU"."DEVICE_INFO" 
   (	"DEVICE_ID" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"DEVICE_ADDRESS" VARCHAR2(18 BYTE) NOT NULL ENABLE, 
	"DEVICE_ARTIFACTS" VARCHAR2(2048 BYTE) NOT NULL ENABLE, 
	"LAST_UPDATE" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "DEVICE_INFO_PK" PRIMARY KEY ("DEVICE_ID")
	 )