/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface LoggedUser { 
    credentialsNonExpired?: boolean;
    enabled?: boolean;
    authorities?: Array<GrantedAuthority>;
    username?: string;
    token?: string;
    password?: string;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
}
