/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Vehicle118 { 
    id?: string;
    parkingId?: string;
    type?: string;
    code?: string;
    managementStatus?: string;
    evolutionStatus?: string;
    asl?: string;
    plateNumber?: string;
    radioSelective?: string;
    physicalFlag?: boolean;
    gpsFlag?: boolean;
    conventionId?: string;
    stopLocation?: string;
    firstMatriculationYear?: number;
    note?: string;
}
