export * from './logging-api';
import { Logger } from './logging-api';
export * from './console-logging.service';
import { ConsoleLogService } from './console-logging.service';
import { RemoteLogService } from './remote-logging.service';
import { NoLogService } from './no-logger';
export * from './console-logging.service';
export * from './remote-logging.service';
export * from './no-logger';
export const UTIL_APIS = [ConsoleLogService, RemoteLogService, NoLogService];
