INSERT INTO DUAL VALUES (1);


INSERT INTO TS_BOOKING_ID (YEAR,BOOKING_ID) values ('17','38369');



--DATI STATICI
INSERT INTO TS_EQUIPMENT (    ID,    COMPACT,    DESCRIPTION,    SELECTED,    WEB_VISIBLE,    TYPE  )  VALUES  (    '115521',    'SPINALE',    'SPINALE',    '0',    '0',    NULL  );

--FINE DATI STATICI
  
INSERT
INTO TO_BOOKING
  (
    ID,
    CODE,
    CREATION_DATE,
    CREATED_BY,
    MODIFIED_BY,
    AUTHORITY_ID1,
    AUTHORITY_ID2,
    DEPARTMENT_ID1,
    DEPARTMENT_ID2,
    TRANSPORT_DATE,
    DATE_FLAG,
    RESCUE_DATE,
    ARRIVE_DATE,
    RESOURCE_ID,
    RETURN_DATE,
    PRIORITY,
    COMPACT_ADDRESS,
    STREET_NAME,
    HOUSE_NUMBER,
    MUNICIPALITY,
    LOCALITY,
    PROVINCE,
    COMPACT_ADDRESS2,
    STREET_NAME2,
    HOUSE_NUMBER2,
    MUNICIPALITY2,
    LOCALITY2,
    PROVINCE2,
    TRANSPORT_TYPE,
    PAT_STATUS,
    COMPANION,
    REQ_TYPE,
    REQ_CONVENTION,
    REQ_DESCR,
    REQ_DETAIL,
    REQ_REF,
    REQ_VAT,
    REQ_CC,
    START_AUTHORITY_ID,
    START_DEPARTMENT_ID,
    START_TYPE,
    START_CONVENTION,
    START_DESCR,
    START_DETAIL,
    START_REFERENCE,
    START_VAT,
    START_CC,
    DEST_TYPE,
    DEST_CONVENTION,
    DEST_DESCR,
    DEST_DETAIL,
    DEST_REFERENCE,
    DEST_VAT,
    DEST_CC,
    ORGANS_FLAG,
    BLOOD,
    VARIOUS_DETAIL,
    STATUS,
    DELETE_SYS_DATE,
    DELETE_USR_NAME,
    DELETE_REASON,
    BOOKING_ID,
    RETURN_READY,
    CICLICAL_ID,
    MEDICAL_REQUEST,
    MEDICAL_AUTHORIZATION,
    DOCTOR_ID,
    DOCTOR_NAME,
    DOCTOR_COST_CENTER,
    PROTECT_RESOURCE_REQUEST,
    RESOURCE_TYPE,
    OPTIONED_PARKING_ID,
    OPTIONED_PARKING,
    ASSIGNED_PARKING_ID,
    ASSIGNED_PARKING,
    HISTORY_FLAG,
    SPECIAL_EQUIPMENT_FLAG,
    NOTE,
    WEB_BOOKING_ID,
    START_TELEPHONE,
    DEST_TELEPHONE,
    REQ_TELEPHONE,
    CATEGORY,
    START_PAVILION_NUMBER,
    START_PAVILION_NAME,
    END_PAVILION_NUMBER,
    END_PAVILION_NAME,
    CHARGE,
    CALLER_TELEPHONE,
    CALLER_SOURCE,
    INDICATIONS,
    MANUTENCOOP_SEND_STATUS,
    EPISODE_RECOVERY_PS,
    WEB_SENDING_USR_DATE
  )
  VALUES
  (
    '173765041',
    '16063351',
    NOW (),
    'ADMIN',
    NULL,
    NULL,
    'E01',
    NULL,
    'NEW_223083756',
    NOW (),
    '0',
    NULL,
    NULL,
    NULL,
    NOW (),
    'NO',
    'ASMN : - - - (RE)',
    '-',
    NULL,
    '-',
    NULL,
    'RE',
    'ASMN - # ACCESSO PS ORDINARI VISITE SPECIALISTICHE -1 : - - - (RE)',
    '-',
    NULL,
    '-',
    NULL,
    'RE',
    'CONSULENZA-ESAME',
    'SEDIA PROPRIA',
    NULL,
    'OSPEDALE',
    'ASMN',
    'ASMN',
    NULL,
    NULL,
    NULL,
    NULL,
    'E01',
    NULL,
    'OSPEDALE',
    'ASMN',
    'ASMN',
    NULL,
    '080903',
    NULL,
    '08090301',
    'OSPEDALE',
    'ASMN',
    'ASMN',
    '# ACCESSO PS ORDINARI VISITE SPECIALISTICHE -1',
    '080903',
    NULL,
    'RE',
    '0',
    '0',
    NULL,
    'PN',
    NULL,
    NULL,
    NULL,
    NULL,
    '0',
    NULL,
    '0',
    '0',
    NULL,
    NULL,
    NULL,
    '0',
    'AMBULANZA / SU RUOTA',
    NULL,
    NULL,
    NULL,
    NULL,
    '0',
    '1',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW ()
  );

  
  INSERT
INTO TO_BOOKING_PATIENT
  (
    ID,
    BOOKING_ID,
    TYPE,
    SURNAME,
    NAME,
    BIRTH_DATE,
    TAX_CODE,
    SANITARY_CODE,
    SEX,
    FIRST_TELEPHONE,
    SECOND_TELEPHONE,
    TICKET,
    STREET_NAME,
    HOUSE_NUMBER,
    LOCALITY,
    MUNICIPALITY,
    PROVINCE,
    ACCESSIBILITY,
    ADDITIONAL_PATIENT_ID
  )
  VALUES
  (
    '173765046',
    '173765041',
    'PAZIENTE',
    'PROVA1',
    'PROVA1',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

  insert into TS_BOOKING_EQUIPMENT(id,booking_id,EQUIPMENT_ID) values ('12345678', '173765041', '115521');
  
  

  
 insert into WEB_BOOKING 
(
ID,
CREATION_DATE,TRANSPORT_DATE,TRANSPORT_TYPE,PAT_STATUS,SURNAME,NAME,SANITARY_CODE,TAX_CODE,START_DESCR,START_DETAIL,START_STREET_NAME,START_HOUSE_NUMBER,START_LOCALITY,START_MUNICIPALITY,
START_PROVINCE,DEST_DESCR,DEST_DETAIL,DEST_STREET_NAME,DEST_HOUSE_NUMBER,DEST_LOCALITY,DEST_MUNICIPALITY,DEST_PROVINCE,REQ_DESCR,REQ_DETAIL,OPTIONED_PARKING,STATUS,STATUS_REASON,DUPLICATED_ID,
NOTE,PATIENT_COMPANION,PATIENT_CHARGEABLE,START_TELEPHONE,DEST_TELEPHONE,REQ_TELEPHONE,DATE_FLAG,PATIENT_TELEPHONE,FLOOR_PART_NUMBER,FLOOR_DEST_NUMBER,LIFT_PART,LIFT_DEST,REFERENCE,ID_EXTERNAL_REF,CODE
) 
values 
(
'17111331',
to_date('21-APR-03','DD-MON-RR'),to_date('21-APR-03','DD-MON-RR'),'TRASF','SEDIA','PROVA WEB','PROVA WEB',null,null,'MAGGIORE','REPARTO  RIANIMAZIONE 11 PIANO','LARGO NIGRISOLI BARTOLO',
'2','PORTO','BOLOGNA','BO','RIZZOLI','TERAPIA INTENSIVA DI ANESTESIA E RIANIMAZIONE','VIA PUPILLI GIULIO CESARE','1',null,'BOLOGNA','BO','MAGGIORE','REPARTO  RIANIMAZIONE 11 PIANO',null,'AC',null,null,
'SERVIZIO DI PROVA',null,'0','2038','6842','2038','0',null,null,null,null,null,null,null,null
);
 

 insert into WEB_BOOKING_EQUIPMENT (ID,WEB_BOOKING_ID,EQUIPMENT_ID,EQUIPMENT_COMPACT) 
 values 
 ('17111336','17111331','1951','POMPA'); 
 
 
 
insert into WEB_BOOKING 
(ID,CREATION_DATE,TRANSPORT_DATE,TRANSPORT_TYPE,PAT_STATUS,SURNAME,NAME,SANITARY_CODE,TAX_CODE,START_DESCR,START_DETAIL,
START_STREET_NAME,START_HOUSE_NUMBER,START_LOCALITY,START_MUNICIPALITY,START_PROVINCE,DEST_DESCR,DEST_DETAIL,DEST_STREET_NAME,
DEST_HOUSE_NUMBER,DEST_LOCALITY,DEST_MUNICIPALITY,DEST_PROVINCE,REQ_DESCR,REQ_DETAIL,OPTIONED_PARKING,STATUS,STATUS_REASON,
DUPLICATED_ID,NOTE,PATIENT_COMPANION,PATIENT_CHARGEABLE,START_TELEPHONE,DEST_TELEPHONE,REQ_TELEPHONE,DATE_FLAG,PATIENT_TELEPHONE,
FLOOR_PART_NUMBER,FLOOR_DEST_NUMBER,LIFT_PART,LIFT_DEST,REFERENCE,ID_EXTERNAL_REF,CODE) 
values 
('173781316',to_date('13-APR-17','DD-MON-RR'),to_date('24-MAR-17','DD-MON-RR'),'CONSULENZA',null,'ANDREOLI','ANNA','NDRNNA29A64D548D',
'NDRNNA29A64D548D','Ambulatorio per l''infertilitÃ  maschile - Ambulatorio per l''inf',null,'Via Massarenti ',null,null,'Bologna ',
'BO ','Anestesiologia e Rianimazione - Anestesiologia Rianimazione - Ca',null,'Via Massarenti ',null,null,'Bologna ','BO ',null,null,
null,'UR',null,null,'nota reinviata','MEDICO SCORTA ',null,null,null,'note richiedente',null,null,null,null,null,null,null,'2001',null);

insert into WEB_BOOKING 
(ID,CREATION_DATE,TRANSPORT_DATE,TRANSPORT_TYPE,PAT_STATUS,SURNAME,NAME,SANITARY_CODE,TAX_CODE,START_DESCR,START_DETAIL,
START_STREET_NAME,START_HOUSE_NUMBER,START_LOCALITY,START_MUNICIPALITY,START_PROVINCE,DEST_DESCR,DEST_DETAIL,DEST_STREET_NAME,
DEST_HOUSE_NUMBER,DEST_LOCALITY,DEST_MUNICIPALITY,DEST_PROVINCE,REQ_DESCR,REQ_DETAIL,OPTIONED_PARKING,STATUS,STATUS_REASON,
DUPLICATED_ID,NOTE,PATIENT_COMPANION,PATIENT_CHARGEABLE,START_TELEPHONE,DEST_TELEPHONE,REQ_TELEPHONE,DATE_FLAG,PATIENT_TELEPHONE,
FLOOR_PART_NUMBER,FLOOR_DEST_NUMBER,LIFT_PART,LIFT_DEST,REFERENCE,ID_EXTERNAL_REF,CODE) 
values 
('173781336',to_date('14-APR-17','DD-MON-RR'),to_date('24-MAR-17','DD-MON-RR'),'CONSULENZA',null,'ANDREOLI','ANNA','NDRNNA29A64D548D',
'NDRNNA29A64D548D','Ambulatorio per l''infertilitÃ  maschile - Ambulatorio per l''inf',null,'Via Massarenti ',null,null,'Bologna '
,'BO ','Anestesiologia e Rianimazione - Anestesiologia Rianimazione - Ca',null,'Via Massarenti ',null,null,'Bologna ','BO ',null,null,
null,'UR',null,null,'note','MEDICO SCORTA ',null,null,null,'note richiedente',null,null,null,null,null,null,null,'2001',null);

insert into WEB_BOOKING 
(ID,CREATION_DATE,TRANSPORT_DATE,TRANSPORT_TYPE,PAT_STATUS,SURNAME,NAME,SANITARY_CODE,TAX_CODE,START_DESCR,START_DETAIL,
START_STREET_NAME,START_HOUSE_NUMBER,START_LOCALITY,START_MUNICIPALITY,START_PROVINCE,DEST_DESCR,DEST_DETAIL,DEST_STREET_NAME,
DEST_HOUSE_NUMBER,DEST_LOCALITY,DEST_MUNICIPALITY,DEST_PROVINCE,REQ_DESCR,REQ_DETAIL,OPTIONED_PARKING,STATUS,STATUS_REASON,
DUPLICATED_ID,NOTE,PATIENT_COMPANION,PATIENT_CHARGEABLE,START_TELEPHONE,DEST_TELEPHONE,REQ_TELEPHONE,DATE_FLAG,PATIENT_TELEPHONE,
FLOOR_PART_NUMBER,FLOOR_DEST_NUMBER,LIFT_PART,LIFT_DEST,REFERENCE,ID_EXTERNAL_REF,CODE) 
values 
('173781341',to_date('14-APR-17','DD-MON-RR'),to_date('24-MAR-17','DD-MON-RR'),'CONSULENZA',null,'ANDREOLI','ANNA','NDRNNA29A64D548D',
'NDRNNA29A64D548D','Ambulatorio per l''infertilitÃ  maschile - Ambulatorio per l''inf',null,'Via Massarenti ',null,null,'Bologna ',
'BO ','Anestesiologia e Rianimazione - Anestesiologia Rianimazione - Ca',null,'Via Massarenti ',null,null,'Bologna ','BO ',null,null,
null,'UR',null,null,'note','MEDICO SCORTA ',null,null,null,'note richiedente',null,null,null,null,null,null,null,'2001',null);

  
 
 
 