/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CiclicalRequestDTO { 
    bookingId?: string;
    ciclicalId?: string;
    fromDate?: Date;
    toDate?: Date;
    dayDate?: Date;
    days?: Array<string>;
    loggedUser?: string;
    status?: string;
    note?: string;
    time?: string;
    phase?: number;
    endCompoundAddress?: string;
    endStreetName?: string;
    endHouseNumber?: string;
    endMunicipality?: string;
    endLocality?: string;
    endProvince?: string;
    endType?: string;
    endConvention?: string;
    endDescription?: string;
    endDetail?: string;
    endReference?: string;
    endVat?: string;
    endCc?: string;
    endAuthorityId?: string;
    endDepartmentId?: string;
    endPavilionNumber?: string;
    endPavilionName?: string;
}
