/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientBookingDTO { 
    id?: string;
    bookingId?: string;
    name?: string;
    surname?: string;
    taxCode?: string;
    sanitaryCode?: string;
    firstTelephone?: string;
    sex?: string;
    ticket?: boolean;
    patientTel?: string;
    additionalPatientId?: string;
    streetName?: string;
    houseNumber?: string;
    birthDate?: Date;
    locality?: string;
    municipality?: string;
    province?: string;
    accessibility?: string;
    type?: string;
    secondTelephone?: string;
}
