
CREATE TABLESPACE CORRENTE DATAFILE 'C:\develope\118\DB\web118_clu_test.ORA' SIZE 10M REUSE 
    AUTOEXTEND 
    ON NEXT  5M  EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO
	/

CREATE USER web118_clu_test
  IDENTIFIED BY web118_clu_test
  DEFAULT TABLESPACE CORRENTE
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
/
  GRANT CONNECT TO web118_clu_test;
  GRANT DBA TO web118_clu_test;
  GRANT RESOURCE TO web118_clu_test;
  ALTER USER web118_clu_test DEFAULT ROLE ALL;

  GRANT CREATE ANY MATERIALIZED VIEW TO web118_clu_test;
  GRANT CREATE ANY SYNONYM TO web118_clu_test;
  GRANT CREATE MATERIALIZED VIEW TO web118_clu_test;
  GRANT CREATE SEQUENCE TO web118_clu_test;
  GRANT CREATE VIEW TO web118_clu_test;
  GRANT DROP ANY SYNONYM TO web118_clu_test;
  GRANT SELECT ANY DICTIONARY TO web118_clu_test;
  GRANT UNLIMITED TABLESPACE TO web118_clu_test;
  
  --IMP SYSTEM/test@web118_clu_test FILE=C:\develope\118\web118_clu_bologna.dmp FROMUSER=web118_clu TOUSER=web118_clu_test GRANTS=Y log =C:\develope\118\web118_clu_bologna.log
