/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDTO } from './messageDTO';
import { VehicleDirectAssignmentDTO } from './vehicleDirectAssignmentDTO';


export interface GenericResultDTOVehicleDirectAssignmentDTO { 
    result?: VehicleDirectAssignmentDTO;
    resultList?: Array<VehicleDirectAssignmentDTO>;
    msgList?: Array<MessageDTO>;
}
