ALTER TABLE  DAE_FIRST_RESPONDER
 ADD (SILENT  NUMBER);
 
   ALTER TABLE  DAE_FIRST_RESPONDER
 ADD (SILENT_FROM  VARCHAR2(10));
 
   ALTER TABLE  DAE_FIRST_RESPONDER
 ADD (SILENT_TO VARCHAR2(10));
 
 ALTER TABLE  DAE_EVENT
 ADD (LUOGO  VARCHAR2(64));
 
-- da inserire sul db di produzione
 ALTER TABLE web118_clu.DAE_ALERT
 ADD (SYNTHESIS_PLACE  VARCHAR2(64));