/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrewMemberDTO { 
    id: string;
    name?: string;
    surname?: string;
    task?: string;
    sex?: string;
    birthdate?: Date;
    adress?: string;
    country?: string;
    password?: string;
    badge?: string;
    taskDetail?: string;
    deleted?: boolean;
    oldId?: string;
    member?: string;
}
