CREATE TABLE DAE_RESPONSABILE_PROVINCIA
(
   ID               VARCHAR2 (64) NOT NULL,
   nome        		VARCHAR2 (64),
   cognome        	VARCHAR2 (64),
   email        	VARCHAR2 (256) NOT NULL,
   PROVINCIA_ID   	VARCHAR2 (64)  NOT NULL,
   CONSTRAINT PK_RESPONSABILE_PROVINCIA_ID PRIMARY KEY (ID),
   CONSTRAINT FK_RESPONSABILE_PROV_PROV_ID FOREIGN KEY
      (PROVINCIA_ID)
       REFERENCES DAE_PROVINCIA (ID)
);