sequenceDiagram
    alt is logged    	 
        Operatore->>SearchDocumentBtn: onClick()
        SearchDocumentBtn-->>Operatore: return
        SearchDocumentBtn->>SearchDocumentCtrl: searchDocuments(filter)        
        SearchDocumentCtrl->>DocumentApiService: listDocument(filter)
        DocumentApiService-->>SearchDocumentCtrl: document list (state NOT CLOSED)
    else is not logged    	
    	DocumentApiService-->>Operatore: forward to login page
    end