/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressBookingDTO } from './addressBookingDTO';
import { PatientBookingDTO } from './patientBookingDTO';
import { ReqBookingDTO } from './reqBookingDTO';
import { Value } from './value';


export interface BookingDTO { 
    duplicable?: boolean;
    automaticMerge?: boolean;
    updateCiclicalMatrix?: boolean;
    id?: string;
    loggedUser?: string;
    code?: string;
    status?: string;
    priority: string;
    patientStatus: string;
    patientCompare?: string;
    creationDate?: Date;
    creationUser?: string;
    transportDate: Date;
    hourTransport?: Date;
    returnDate?: Date;
    hourReturn?: Date;
    transportType: string;
    phase: string;
    equipmentList?: Array<Value>;
    dpiList?: Array<Value>;
    startAddress: AddressBookingDTO;
    endAddress: AddressBookingDTO;
    patientBooking?: PatientBookingDTO;
    organsFlag?: boolean;
    blood?: boolean;
    variousDetail?: string;
    req: ReqBookingDTO;
    resourceType?: string;
    optionedParkingCode?: string;
    assignedParkingCode?: string;
    protectResourceRequest?: boolean;
    medicalRequest?: boolean;
    medicalAuthorization?: boolean;
    doctorName?: string;
    doctorCc?: string;
    note?: string;
    indications?: string;
    charge?: string;
    ciclicalId?: string;
    modifyUsername?: string;
    deleteUsername?: string;
    deletedate?: Date;
    createdAsReturn?: boolean;
    returnReady?: boolean;
    webCode?: string;
    bookingId?: string;
    ciclicalBookingId?: string;
    source?: string;
    deleteReason?: string;
}
