/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcknowledgeResp { 
    out?: AcknowledgeResp.OutEnum;
}
export namespace AcknowledgeResp {
    export type OutEnum = 'ACK' | 'NAK' | 'ERROR';
    export const OutEnum = {
        ACK: 'ACK' as OutEnum,
        NAK: 'NAK' as OutEnum,
        ERROR: 'ERROR' as OutEnum
    };
}
