/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrewMemberFilterDTO { 
    name?: string;
    surname?: string;
    task?: string;
    excludeDeletedFlag?: boolean;
    excludeIdListFlag?: boolean;
    idList?: Array<string>;
}
