/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuItemValue } from './menuItemValue';
import { Value } from './value';


export interface OverviewTailReturnsDTO { 
    columnT?: Value;
    columnA?: Value;
    statusOverview?: number;
    rowStyle?: { [key: string]: string; };
    popupMenu?: Array<MenuItemValue>;
    id?: string;
    code?: string;
    status?: string;
    priority?: string;
    patientStatus?: string;
    patientCompare?: string;
    transportDate?: Date;
    returnDate?: Date;
    transportType?: string;
    phase?: string;
    startAddress?: string;
    endAddress?: string;
    patientName?: string;
    patientSurname?: string;
    postazione?: string;
    convention?: string;
    doctorName?: string;
    denominazionePaziente?: string;
    riferimento?: string;
    note?: string;
    creationDate?: Date;
    indicazioni?: string;
    attrezzature?: string;
    ciclicalId?: string;
    specialEquipment?: string;
    bookingId?: string;
    source?: string;
    returnReady?: boolean;
}
