server:
  port: 8081
  servlet:
    contextPath: /dev  
spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
