spring:
  profiles:
    active:
    - dev
  application:
    name: city-service
counter-service:
  eureka:
    enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka