spring:
  profiles:
    active:
    - dev
  application:
    name: city-service
counter-service:
  ribbon:
    listOfServers: http://localhost:9090,http://localhost:9091
  eureka:
    enabled: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka