debug: true
logging:
  level:
    root: info
server:
  port: 8080
  servlet:
    contextPath: /prod
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productiondb?useSsl=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    initialization-mode: always
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql