ALTER TABLE  DAE_DAE
 ADD (DISPONIBILITA_PERMANENTE  NUMBER);

 ALTER TABLE DAE_EVENT
 ADD (DATA_ARRIVO_AMBULANZA  TIMESTAMP(6));
 
 ALTER TABLE DAE_RUOLO
 ADD (GLOBAL_SEARCH  NUMBER);

ALTER TABLE DAE_RUOLO
 ADD (GLOBAL_SAVE  NUMBER);