/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OverviewTailReturnFilterDTO { 
    ids?: Array<string>;
    allBookingFlag?: boolean;
    todayBookingFlag?: boolean;
    tomorrowBookingFlag?: boolean;
    historicalArchiveFlag?: boolean;
    fuoriBologna?: boolean;
    transportDateStart?: Date;
    transportDateStop?: Date;
    transportDate?: Date;
    intraOspFlag?: boolean;
    interOspFlag?: boolean;
    codeList?: Array<string>;
    timeSlotList?: Array<OverviewTailReturnFilterDTO.TimeSlotListEnum>;
    typeTxtList?: Array<string>;
    conventionTxtList?: Array<string>;
    startAddressTxtList?: Array<string>;
    endAddressTxtList?: Array<string>;
    patientSurnameTxtList?: Array<string>;
    cyclicalBookingFlag?: boolean;
    startIntraOspFlag?: boolean;
    startExtraOspFlag?: boolean;
    endIntraOspFlag?: boolean;
    endExtraOspFlag?: boolean;
    sinottico?: boolean;
    returnReady?: boolean;
}
export namespace OverviewTailReturnFilterDTO {
    export type TimeSlotListEnum = 'AM' | 'PM' | 'ND';
    export const TimeSlotListEnum = {
        AM: 'AM' as TimeSlotListEnum,
        PM: 'PM' as TimeSlotListEnum,
        ND: 'ND' as TimeSlotListEnum
    };
}
