package it.eng.areas.ems.sdodaeservices.delegate.model;

public enum MailTemplateEnum {
	RESET_PWD_MAIL_TEMPLATE, //
	NEW_PWD_MAIL_TEMPLATE, //
	ENABLE_FR_MAIL_TEMPLATE, //
	NEW_USER_MAIL_TEMPLATE, //
	NEW_PASSWORD_MAIL_TEMPLATE, //
	SCADENZA_SEMESTRALE_MAIL_TEMPLATE, //
	SCADENZA_MANUTENZIONE_MAIL_TEMPLATE, //
	MANUTENZIONE_SCADUTA_MAIL_TEMPLATE, //
	PASSWORD_CHANGED_HTML_TEMPLATE, //
	PASSWORD_CHANGED_ERROR_HTML_TEMPLATE, //
	PASSWORD_NOT_CHANGED_HTML_TEMPLATE, //

	ADMINISTRATOR_NEW_USER_MAIL_TEMPLATE, //
	ADMINISTRATOR_NEW_DAE_MAIL_TEMPLATE, //
	ADMINISTRATOR_DAE_FAULT_MAIL_TEMPLATE, //

	RESPONSIBLE_DAE_VALIDATION_TEMPLATE, //
	DAE_FAULT_OPEN_MAIL_TEMPLATE, //
	DAE_FAULT_CLOSED_MAIL_TEMPLATE, //

	FR_ACTIVATED_HTML_TEMPLATE, //
	FR_ACTIVATION_ERROR_HTML_TEMPLATE, //
	FR_NOT_ACTIVATED_HTML_TEMPLATE, //

	FR_PLACE_ARRIVAL_MAIL_TEMPLATE, //

	FR_ACCEPTED_EVENT,//
}
