/**
 * Swagger Maven Plugin Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OverviewCiclicalFilterDTO { 
    status?: string;
    transportedPatient?: string;
    bookingCode?: string;
    fromDate?: Date;
    toDate?: Date;
    transportDate?: Date;
    parkingId?: string;
    parkingCode?: string;
    allCiclicalFlag?: boolean;
    todayCiclicalFlag?: boolean;
    days?: Array<string>;
    daysStruct?: Array<any>;
}
